### ISSUE TITLE
Lights go through Cracks

### ISSUE THREAD

**Issue by hjc2** [hjc2/rats#43]
![image](https://github.com/user-attachments/assets/eff32815-e90b-47c4-8c41-7fd3136b7555)

**Comment by gayatri-r** [comment]
<img width="255" alt="Screenshot 2024-11-11 at 11 59 51 AM" src="https://github.com/user-attachments/assets/f6a8d9d8-39ef-4544-b806-d5d867a04643">

**Comment by hjc2** [comment]
option - make box a little smaller
